version: '3'
services:
  redis-slave1:
    image: redis:3.2
    container_name: redis-slave1
    command: redis-server --appendonly yes
    volumes:
      - /mydata/redis-slave1/:/data
    ports:
      - 6380:6379
    network_mode: host
  redis-slave2:
    image: redis:3.2
    container_name: redis-slave2
    command: redis-server --appendonly yes
    volumes:
      - /mydata/redis-slave2/:/data
    ports:
      - 6381:6379
    network_mode: host