version: '3'
services:
  es1:
    # es镜像版本，我之前docker拉取的版本是7.2.0 你需要在这里修改为自己的版本
    image: elasticsearch:7.5.2
    # 容器名称
    container_name: es1
    privileged: true
    # 启动时的环境参数 因为我的服务器配置较低所以分配了128m
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    # 挂载数据卷
    volumes:
      # 挂载data
      - ./data/node0:/usr/share/elasticsearch/data
      # 挂载自己的配置文件
      - ./config/node0/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      # 挂载日志文件
      - ./logs/node0:/usr/share/elasticsearch/logs
      # 端口映射关系
    ports:
      - 9200:9200
    # 网络信息
    networks:
      - esnet
  es2:
    # es镜像版本，我之前docker拉取的版本是7.2.0 你需要在这里修改为自己的版本
    image: elasticsearch:7.5.2
    # 容器名称
    container_name: es2
    privileged: true
    # 启动时的环境参数 因为我的服务器配置较低所以分配了128m
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    # 挂载数据卷
    volumes:
      # 挂载data
      - ./data/node1:/usr/share/elasticsearch/data
      # 挂载自己的配置文件
      - ./config/node1/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      # 挂载日志文件
      - ./logs/node1:/usr/share/elasticsearch/logs
      # 端口映射关系
    ports:
      - 9201:9200
    # 网络信息
    networks:
      - esnet
  es3:
    image: elasticsearch:7.5.2
    container_name: es3
    privileged: true
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/node2:/usr/share/elasticsearch/data
      - ./config/node2/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./logs/node2:/usr/share/elasticsearch/logs
    ports:
      - 9202:9200
    links:
      - es1
    networks:
      - esnet
  kibana:
    image: kibana:7.5.2
    container_name: kibana
    depends_on:
      - es1
    environment:
      - ELASTICSEARCH_HOSTS=http://es1:9200
      # 需要将Kibana配置文件中的小写转换成大写，然后这个才能用于变量，才能被设置到
      - I18N_LOCALE=zh-CN
      - xpack.monitoring.ui.container.elasticsearch.enabled=false
    ports:
      - 5601:5601
    networks:
      - esnet
  kibana2:
    image: kibana:7.5.2
    container_name: kibana2
    depends_on:
      - es2
    environment:
      - ELASTICSEARCH_HOSTS=http://es2:9200
      # 需要将Kibana配置文件中的小写转换成大写，然后这个才能用于变量，才能被设置到
      - I18N_LOCALE=zh-CN
      - xpack.monitoring.ui.container.elasticsearch.enabled=false
    ports:
      - 5602:5601
    networks:
      - esnet
  kibana3:
    image: kibana:7.5.2
    container_name: kibana3
    depends_on:
      - es3
    environment:
      - ELASTICSEARCH_HOSTS=http://es3:9200
      # 需要将Kibana配置文件中的小写转换成大写，然后这个才能用于变量，才能被设置到
      - I18N_LOCALE=zh-CN
      - xpack.monitoring.ui.container.elasticsearch.enabled=false
    ports:
      - 5603:5601
    networks:
      - esnet
# 使用桥接的网络连接方式
networks:
  esnet:
    driver: bridge
