spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:sqlserver://192.168.0.187:1433;databasename=tikbee
    username: sa
    password: 123456
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
server:
  port: 8131
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: false
    cache-enabled: false
  mapper-locations: classpath:mapper/*.xml
  #  type-aliases-package: com.sunsco.entity.model
  global-config:
    db-config:
      #      field-strategy: not_empty
      table-underline: false