spring:
  application:
    name: service-gateway
  cloud:
    loadbalancer:
      retry:
        enabled: true #开启失败重试
    gateway:
      discovery:
        locator:
          #//当访问http://网关地址/服务名称（大写）/**地址会自动转发到http://服务名称（大写）/**地址，如果为false就不会自动转发
          enabled: true
          #为true表示服务名称（小写）
          lower-case-service-id: true
      routes:
        - id: service-hi
          #lb代表从注册中心获取服务，后面接的就是你需要转发到的服务名称 不能填uri只能是服务名称
          uri: lb://SERVICE-HI
          predicates:
            - Path=/demo/**
            filters:
              - name: Retry
                args:
                  #在Eureka注册列表中有一个节点挂掉了，在短时间内，列表没有更新，还会调用挂掉的节点，可以通过失败重试调用其他节点
                  retries: 3
                  statuses: BAD_GATEWAY
server:
  port: 8666
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
