server:
  port: 8763
spring:
  application:
    name: service-hi
  data:
    elasticsearch:
      #开启 Elasticsearch 仓库(默认值:true)
      repositories:
        enabled: true
      #默认 9300 是 Java 客户端的端口。9200 是支持 Restful HTTP 的接口
      cluster-nodes: 192.168.0.98:9300
      #集群名(默认值: elasticsearch)
      cluster-name: elkcs
      #集群节点地址列表，用逗号分隔。如果没有指定，就启动一个客户端节点
      properties:
        #存储索引的位置
        path:
          home: /data/project/target/elastic
        transport:
          tcp:
            connect_timeout: 120s
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

elasticsearch:
  ip: 192.168.0.127:9200